"""empty message

Revision ID: 0f4b6d836555
Revises: 
Create Date: 2025-04-08 13:03:33.740447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f4b6d836555'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=True),
    sa.Column('location', sa.Enum('hall', 'terrace', 'vip_hall', name='places'), nullable=False),
    sa.CheckConstraint('seats > 0', name='check_seats_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Table_name'), 'Table', ['name'], unique=True)
    op.create_table('Reservation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=128), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=False),
    sa.Column('reservation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['table_id'], ['Table.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Reservation_table_id'), 'Reservation', ['table_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Reservation_table_id'), table_name='Reservation')
    op.drop_table('Reservation')
    op.drop_index(op.f('ix_Table_name'), table_name='Table')
    op.drop_table('Table')
    # ### end Alembic commands ###
